apiVersion: apps/v1
kind: Deployment
metadata:
    name: e-commerce
spec:
    replicas: 1
    selector:
        matchLabels:
            app: e-commerce
    template:
        metadata:
            labels:
                app: e-commerce
        spec:
            containers:
                - name: e-commerce
                  image: jayhawk24/e-commerce
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - secretRef:
                            name: prod-secrets
# ... Deployment YAML definition
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
    name: e-commerce
spec:
    selector:
        app: knote
    type: LoadBalancer
    ports:
        - port: 3000
          targetPort: 3000
          nodePort: 30000
